add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})

set_languages("c11", "cxx20")
set_toolchains("clang")

add_requires("fmt")
add_requires("boost")
add_requires("jsoncpp")
add_requires("argparse")

target("saifcpp")
  set_kind("static")
  add_includedirs("include")
  add_cxxflags("-march=native")
  add_files("src/saifcpp/*.cpp")
  add_installfiles("include/*.h", {prefixdir = "include"})
  add_packages("fmt")
  add_packages("boost")
  add_packages("jsoncpp")

target("saif2json")
  set_kind("binary")
  add_includedirs("include")
  add_cxxflags("-march=native")
  add_files("src/saif2json/*.cpp")
  add_deps("saifcpp")
  add_packages("fmt")
  add_packages("boost")
  add_packages("jsoncpp")
  add_packages("argparse")